Add ad-hoc report generation (#2)
* Update generic-report-generator.yml
* Create dotnet-diag-adhoc.yml

diff --git a/.github/workflows/generic-report-generator.yml b/.github/workflows/generic-report-generator.yml
--- a/.github/workflows/generic-report-generator.yml
+++ b/.github/workflows/generic-report-generator.yml
@@ -4,11 +4,17 @@ on:
   workflow_call:
     inputs:
         configName:
+          description: 'Base name of the config without json qualifier.'
           required: true
           type: string
         # TODO: this could escape the root.
         reportFolderRelativePath:
+          description: 'Folder to look for latest cached result in.'
           required: true
+          type: string
+        oldConfigName:
+          description: 'Optional. Name of the report in reportFolderRelativePath to use as the base cache report. If passed, results are only available as a pipeline artifact.'
+          required: false
           type: string
 
 permissions:
@@ -25,21 +31,44 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
+    - name: Validate Inputs
+      id: validate-inputs
+      run: |
+        if [ -n "${{ inputs.oldConfigName }}" ]; then
+          file=${{ format('{0}/{1}', inputs.reportFolderRelativePath, inputs.oldConfigName) }}
+          [ ! -f $file ] && echo "Cached result \"$file\" not found" && exit 1
+        else
+          file=$(find ${{ inputs.reportFolderRelativePath }} -maxdepth 1 -name '*.json' | sort -r | head -1)
+          [ -z "$file" ] && echo "No cached result found."
+        fi
+        [ -n "$file" ] && echo "Using cached result: \"$file\""
+        echo "Using config: \"Configs/${{ inputs.configName }}.json\""
+        echo "file=$file" >> $GITHUB_OUTPUT
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 6.0.x
     - name: Build
       run: |
-        echo "Using config: "Configs/${{ inputs.configName }}.json""
-        file=$(find ${{ inputs.reportFolderRelativePath }} -maxdepth 1 -name '*.json' | sort -r | head -1)
-        [ -z "$file" ] && echo "No cached result found."
-        [ -n "$file" ] && echo "Using cached result: "$file""
-        dotnet run -c release -- "Configs/${{ inputs.configName }}.json" "$file"
+        dotnet run -c release -- "Configs/${{ inputs.configName }}.json" "${{ steps.validate-inputs.outputs.file }}"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - name: Upload Results
+      if: ${{ inputs.oldConfigName == '' }}
       run: |
         git add *reports
         git -c user.name="Report Generator" -c user.email="juan@hoyosjs.com" commit -m "Add report for diagnostics $(date +'%Y-%m-%d')"
         git push
+    - name: Get new report name
+      if: ${{ inputs.oldConfigName != '' }}
+      run: |
+        report=$(find ${{ inputs.reportFolderRelativePath }} -maxdepth 1 -name '*.md' | sort -r | head -1)
+        echo "report=$report" >> $GITHUB_OUTPUT
+    - name: Upload Results as pipeline artifact
+      if: ${{ inputs.oldConfigName != '' }}
+      uses: actions/upload-artifact@v3.1.2
+      with:
+        name: report
+        path: ${{ inputs.reportFolderRelativePath }}/${{ steps.validate-inputs.report.file }}
+        if-no-files-found: error
+        retention-days: 5
